// packages/editor-for-vue2/src/components/Toolbar.vue
<script lang="ts">
import { createToolbar, DomEditor, IDomEditor } from '@wangeditor-next/editor'
import Vue from 'vue'

export default Vue.extend({
  name: 'Toolbar',
  render(h) {
    return h('div', { ref: 'box' })
  },
  props: {
    editor: {
      type: Object,
      default: undefined,
    },
    defaultConfig: {
      type: Object,
      default: () => ({}),
    },
    mode: {
      type: String,
      default: 'default',
    },
  },
  methods: {
    // 创建 toolbar
    create(editor: IDomEditor) {
      if (this.$refs.box == null) {
        return
      }
      if (editor == null) {
        return
      }
      if (DomEditor.getToolbar(editor)) {
        return
      } // 不重复创建

      createToolbar({
        editor,
        selector: this.$refs.box as Element,
        config: this.defaultConfig || {},
        mode: this.mode || 'default',
      })
    },
  },
  watch: {
    editor: {
      handler(e: IDomEditor | null) {
        if (e == null) {
          return
        }
        this.create(e)
      },
      immediate: true,
    },
  },
})
</script>

// packages/editor-for-react/src/components/Toolbar.tsx
/**
 * @description toolbar react component
 * @author wangfupeng
 */

import * as wangEditor from '@wangeditor-next/editor'
import React, { useEffect, useRef } from 'react'

interface IProps {
  editor: wangEditor.IDomEditor | null
  defaultConfig?: Partial<wangEditor.IToolbarConfig>
  mode?: string
  style?: object
  className?: string
}

function ToolbarComponent(props: IProps) {
  const {
    editor, defaultConfig = {}, mode = 'default', style = {}, className,
  } = props
  const ref = useRef<HTMLDivElement>(null)
  const toolbarRef = useRef<wangEditor.Toolbar | null>(null)

  useEffect(() => {
    if (ref.current == null) { return }
    if (editor == null) { return }
    if (ref.current?.getAttribute('data-w-e-toolbar')) { return }

    toolbarRef.current = wangEditor.createToolbar({
      editor,
      selector: ref.current,
      config: defaultConfig,
      mode,
    })
  }, [editor, defaultConfig, mode])

  useEffect(() => {
    return () => {
      if (toolbarRef.current) {
        toolbarRef.current.destroy()
      }
    }
  }, [])

  return <div style={style} ref={ref} className={className}></div>
}

export default ToolbarComponent
